disease_prediction/config/urls.py
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(('disease_prediction.authentication.urls', 'authentication'), namespace='authentication')),
    path('dashboard/', include(('disease_prediction.dashboard.urls', 'dashboard'), namespace='dashboard')),
    path('', include(('disease_prediction.pages.urls', 'pages'), namespace='pages')),
]

if settings.DEBUG:
    try:
        import debug_toolbar
    except ImportError:
        pass
    else:
        urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns

disease_prediction/disease_prediction/authentication/urls.py
from django.urls import path, reverse_lazy

from django.contrib.auth import views as auth_views

from disease_prediction.authentication.views.login import CustomLoginView
from disease_prediction.authentication.views.registration import RegistrationView, StateJsonView

from .views.oauth import trackfly_oauth_callback
urlpatterns = [
    path('trackfly/callback/', trackfly_oauth_callback, name='trackfly-callback'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.logout_then_login, name='logout'),
    path('register/', RegistrationView.as_view(), name='register'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('forgot-password/',
         auth_views.PasswordResetView.as_view(
             template_name='authentication/forgot_password.html',
             html_email_template_name='emails/password_reset_email.html',
             email_template_name='emails/password_reset_email.html',
             subject_template_name='emails/password_reset_subject.txt',
             success_url=reverse_lazy('authentication:forgot_password_done')
         ),
         name='forgot_password'),

    path('forgot-password/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='authentication/forgot_password_done.html',
    ), name='forgot_password_done'),

    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('authentication:password_reset_complete'),
            template_name='authentication/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),

    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='authentication/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),

    path('state/', StateJsonView.as_view(), name='state'),
]

disease_prediction/disease_prediction/dashboard/urls.py
from django.urls import path

from disease_prediction.dashboard.views import DashboardView

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
]

disease_prediction/templates/snippets/footer.html
<footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        Trackfly
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; {% now "Y" %} <a href="https://trackfly.com">trackfly.com</a>.</strong> All rights reserved.
</footer>

disease_prediction/templates/snippets/main_sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="{% static 'img/trackfly-small-logo.png' %}" alt="Trackfly"
             class="brand-image ml-2"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Trackfly</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <!-- <div class="user-panel mt-3 pb-1 mb-3 d-flex">
            <div class="image">
                <img src="{% static 'img/male.png' %}" class="img-circle elevation-2"
                     alt="User Image">
            </div>
            <div class="ml-3">
                <a href="#" class="d-block">Alexander Pierce</a>
                <a href="{% url 'authentication:logout' %}" class="d-block mt-1"> <i class="fas fa-sign-out-alt"></i> Logout</a>
            </div>
        </div>-->

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">
                <li class="nav-item">
                    <a href="{% url 'dashboard:dashboard' %}" class="nav-link">
                        <i class="nav-icon fas fa-chart-line"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-upload"></i>
                        <p>
                            Import CSV
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'product:catalog' %} " class="nav-link">
                        <i class="nav-icon fas fa-list"></i>
                           <p>
                               Catalogs
                           </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Directory
                        </p>
                    </a>
                </li>

            </ul>
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            User
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{%url 'authentication:logout' %}" class="nav-link" onclick="">
                        <i class="nav-icon fa fa-sign-out-alt"></i>
                        <p>
                            Logout
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

disease_prediction/templates/snippets/messages.html
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
</div>
{% endfor %}